const userActionTypes = {
  SET_USER_TOKENS: "SET_USER_TOKENS",
  SET_USER_DETAILS: "SET_USER_DETAILS",
  SET_USER_AVATAR: "SET_USER_AVATAR",
  SET_USER_EMAIL_VERIFIED: "SET_USER_EMAIL_VERIFIED",
  LOG_USER_OUT: "LOG_USER_OUT",
};

export default userActionTypes;
